Repository spatie/laravel-activitylog, pull requests merged in 2019-07, with the labels that each got.

#563 fix existing description
  src/ActivityLogger.php
  tests/LogsActivityTest.php
Labels: bug

#569 Fix for deprecated helpers
  tests/DetectsChangesTest.php
Labels: bug, next release

#568 Add database connection
  config/activitylog.php
  migrations/create_activity_log_table.php.stub
  phpunit.xml.dist
  src/Models/Activity.php
  tests/CustomDatabaseConnectionActivityModelTest.php
  tests/Models/CustomDatabaseConnectionOnActivityModel.php
  tests/TestCase.php
Labels: enhancement, next release
