Repository spatie/laravel-activitylog, pull requests merged in 2022-04, with the labels that each got.

#997 Add Conditionable to ActivityLogger
  src/ActivityLogger.php
Labels: enhancement

#1035 little typo on the logging-model-events.md page
  docs/advanced-usage/logging-model-events.md
Labels: documentation

#1038 Use `data_get()` for placeholder replacement instead of `Arr::get()`
  src/ActivityLogger.php
  tests/ActivityLoggerTest.php
  tests/Models/Article.php
Labels: bug, enhancement
